#Patient Data Analyzer

Tasks

1️⃣ Print first rows

df.head()

2️⃣ Find average sugar level

3️⃣ Find correlation between SugarLevel and Diabetes

4️⃣ Write one insight sentence

In [3]:
import pandas as pd
import numpy as np


data = {
    "Age":[25,34,45,50,23,40],
    "SugarLevel":[85,120,150,160,90,140],
    "BMI":[22,28,31,30,24,29],
    "Diabetes":[0,1,1,1,0,1]
}

In [5]:
df = pd.DataFrame(data)
print(df)

# 0 means negative and 1 means positive

   Age  SugarLevel  BMI  Diabetes
0   25          85   22         0
1   34         120   28         1
2   45         150   31         1
3   50         160   30         1
4   23          90   24         0
5   40         140   29         1

In [6]:
df.head()

   Age  SugarLevel  BMI  Diabetes
0   25          85   22         0
1   34         120   28         1
2   45         150   31         1
3   50         160   30         1
4   23          90   24         0

In [19]:
df['SugarLevel'].mean()

np.float64(124.16666666666667)

In [40]:
c1 = df['SugarLevel'].corr(df['Diabetes'])
print(f"The correlation blw the sugarlevel and diabetes is : {c1: .2f}")

The correlation blw the sugarlevel and diabetes is :  0.91

In [41]:
C = df['Age'].corr(df['Diabetes'])
print(f"The correlation blw the age and diabetes is : {C: .2f}")
#finding correlation blw age and dibaetes

The correlation blw the age and diabetes is :  0.87

In [42]:
#finding correlation blw age and sugarlevel
C2 = df['Age'].corr(df['SugarLevel'])
print(f"The correlation blw the age and sugarlevel is : {C2: .2f}")

The correlation blw the age and sugarlevel is :  0.99

In [43]:
C3 = df['BMI'].corr(df['Diabetes'])
print(f"The correlation blw the BMI and diabetes is : {C3: .2f}")

The correlation blw the BMI and diabetes is :  0.94

In [44]:
C4= df['BMI'].corr(df['SugarLevel'])
print(f"The correlation blW the BMI and sugarlevel is : {C4: .2f}")

The correlation blW the BMI and sugarlevel is :  0.96

**INSIGHT** :
    
    
    1️⃣ First: Why Your Correlations Look “Too Perfect”

    You reported:

Relationship
| Relationship          | Correlation |
| --------------------- | ----------- |
| Age ↔ SugarLevel      | 0.99        |
| BMI ↔ SugarLevel      | 0.96        |
| BMI ↔ Diabetes        | 0.94        |
| SugarLevel ↔ Diabetes | 0.91        |
| Age ↔ Diabetes        | 0.87        |


**Why?**

Because your dataset only has 6 rows.

When datasets are very small, correlations become unstable and misleading.

Example:

If we had 1000 patients, correlations might look like:




```
# This is formatted as code
```


Feature	   Correlation (with Diabetes)

SugarLevel	  0.68

BMI         	0.41

Age	          0.33






So your intuition that something looks unusual is 100% correct.

That is how a real analyst thinks.

**2️⃣ What the Correlation Matrix Actually Means**

When you calculate correlation for all columns using pandas, you probably ran something like:

df.corr()

This produces a correlation matrix.

Example interpretation:

Feature	Meaning

Age vs SugarLevel

Older people tend to have higher sugar levels


BMI vs Diabetes	Higher

BMI → higher diabetes risk


SugarLevel vs Diabetes

Strong indicator of diabetes

The key idea:

Correlation measures how strongly two variables move together.

Range:

Value	Meaning

+1	Perfect positive

0	No relationship

-1	Perfect negative


**3️⃣ How a Data Scientist Writes Insights**

Your explanation was good, but let me show you the professional way to write it.

Example Insight

**Insight 1**

Higher SugarLevel shows a strong positive correlation with Diabetes (0.91), indicating that blood glucose level is a major indicator of diabetes risk.




**Insight 2**

BMI has a strong correlation with Diabetes (0.94), suggesting that higher body mass index may increase the likelihood of developing diabetes.





**Insight 3**

Age shows a strong relationship with SugarLevel (0.99), implying that blood sugar levels may increase with age in this dataset.

But we must mention an important limitation:

Since the dataset contains only 6 observations, these correlations may not generalize to real-world populations.

This sentence is very important in real data science reports.

**4️⃣ How to Select Specific Correlations**

You asked an important technical question.

Instead of printing all correlations, we can select specific ones.



Example:

Correlation with Diabetes only
df.corr()['Diabetes']

Output example:

Age           0.87
SugarLevel    0.91
BMI           0.94

This tells us which features affect diabetes most.



Correlation between specific variables
 **df[['SugarLevel','BMI','Age']].corr()**

This gives correlation only among selected features.

**5️⃣ Real Data Science Thinking (Important)**

Correlation does NOT mean causation.

Example:

If we see:

Ice Cream Sales ↔ Drowning deaths
Correlation = 0.85

That does NOT mean ice cream causes drowning.

The real cause is summer temperature.

So in your case:

High BMI ↔ Diabetes

This does not mean BMI causes diabetes directly, but it is a risk factor.

# **✈IMPORTANT**

#**ADVANCE Operation**
⏰

### What happened here?
By calling `df.corr()`, Pandas performed **vectorized operations** to compare every column against every other column.
- The result is a table where the value at row **A** and column **B** is the correlation between those two variables.
- Notice the diagonal is all `1.0`, because every variable is perfectly correlated with itself.

In [26]:
# Vectorized approach: Calculate correlation matrix for the entire DataFrame
c3 = df.corr()

print("Full Correlation Matrix (Vectorized):")
display(c3)

Full Correlation Matrix (Vectorized):

                 Age  SugarLevel       BMI  Diabetes
Age         1.000000    0.989118  0.921579  0.869911
SugarLevel  0.989118    1.000000  0.961323  0.905342
BMI         0.921579    0.961323  1.000000  0.943119
Diabetes    0.869911    0.905342  0.943119  1.000000

### How this works:
Instead of looping through columns, `df.corr()` tells Pandas to handle the entire data table at once. This is much faster and cleaner because Pandas uses highly optimized internal C/C++ code to run these calculations in parallel across your CPU.

In [25]:
import pandas as pd

# Creating the DataFrame from your data
df = pd.DataFrame(data)

# One-line vectorized command to calculate all correlations
all_correlations = df.corr()

print("Vectorized Correlation Matrix:")
display(all_correlations)

Vectorized Correlation Matrix:

                 Age  SugarLevel       BMI  Diabetes
Age         1.000000    0.989118  0.921579  0.869911
SugarLevel  0.989118    1.000000  0.961323  0.905342
BMI         0.921579    0.961323  1.000000  0.943119
Diabetes    0.869911    0.905342  0.943119  1.000000

### Why this is 'Vectorized':
When you call `df.corr()`, Pandas doesn't use a Python loop to go through each row. Instead, it uses optimized C-based operations to calculate the relationship between all numeric columns simultaneously. This is the most efficient way to analyze relationships in a dataset.

#**OR U CAN SAY LIKE THIS BELOW ALSO**

In [48]:
df.corr()['Diabetes']
#This tells us which features affect diabetes most.

Age           0.869911
SugarLevel    0.905342
BMI           0.943119
Diabetes      1.000000
Name: Diabetes, dtype: float64

Correlation between specific variables

In [50]:
df[['SugarLevel','BMI','Age']].corr()
#This gives correlation only among selected features.

            SugarLevel       BMI       Age
SugarLevel    1.000000  0.961323  0.989118
BMI           0.961323  1.000000  0.921579
Age           0.989118  0.921579  1.000000

In [55]:
#9️⃣ Mini Practice Task

DATA = [25, 32, 47, 51, 62]

f = np.array(DATA)
print("Mean : ",f.mean())
print("Maximum : ",f.max())
print("MINIMUM: ",f.min())

Mean :  43.4
Maximum :  62
MINIMUM:  25

#**Mini Project 3 — Feature Importance Analyzer**

In [57]:
data1 = {
"Age":[21,35,52,46,28,40,33,60],
"SugarLevel":[80,120,160,150,90,140,110,170],
"BMI":[21,29,33,31,23,30,27,34],
"ExerciseHours":[5,1,0,1,4,2,3,0],
"Diabetes":[0,1,1,1,0,1,0,1]
}
e = pd.DataFrame(data1)
e

   Age  SugarLevel  BMI  ExerciseHours  Diabetes
0   21          80   21              5         0
1   35         120   29              1         1
2   52         160   33              0         1
3   46         150   31              1         1
4   28          90   23              4         0
5   40         140   30              2         1
6   33         110   27              3         0
7   60         170   34              0         1

In [58]:
e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            8 non-null      int64
 1   SugarLevel     8 non-null      int64
 2   BMI            8 non-null      int64
 3   ExerciseHours  8 non-null      int64
 4   Diabetes       8 non-null      int64
dtypes: int64(5)
memory usage: 452.0 bytes

In [61]:
e.dtypes

Age              int64
SugarLevel       int64
BMI              int64
ExerciseHours    int64
Diabetes         int64
dtype: object

In [65]:
e[['Age','SugarLevel','BMI','ExerciseHours','Diabetes']].corr()

                    Age  SugarLevel       BMI  ExerciseHours  Diabetes
Age            1.000000    0.977447  0.956225      -0.918608  0.775982
SugarLevel     0.977447    1.000000  0.983850      -0.939682  0.861489
BMI            0.956225    0.983850  1.000000      -0.973176  0.870435
ExerciseHours -0.918608   -0.939682 -0.973176       1.000000 -0.894427
Diabetes       0.775982    0.861489  0.870435      -0.894427  1.000000

In [71]:
e['Age'].corr(e['Diabetes'])

np.float64(0.7759822449905486)

In [72]:
e.corr()['Diabetes']

Age              0.775982
SugarLevel       0.861489
BMI              0.870435
ExerciseHours   -0.894427
Diabetes         1.000000
Name: Diabetes, dtype: float64

Insight 1

SugarLevel shows strong correlation with diabetes.

Insight 2

ExerciseHours shows negative correlation with diabetes.

Insight 3

BMI is moderately related to diabetes risk.